python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 36 36 36 36 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 0 --unit_pruning_gradient 5.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 36 36 36 36 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 36 36 36 36 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 2 --unit_pruning_gradient 10.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 36 36 36 36 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 5 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 36 36 36 36 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 5 --unit_pruning_gradient 25.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 48 48 48 48 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 0 --unit_pruning_gradient 55.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 48 48 48 48 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 1 --unit_pruning_gradient 65.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 48 48 48 48 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 1 --unit_pruning_gradient 35.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 48 48 48 48 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 2 --unit_pruning_gradient 60.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 48 48 48 48 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 5 --unit_pruning_gradient 15.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 60 60 60 60 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 0 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 60 60 60 60 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 1 --unit_pruning_gradient 50.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 60 60 60 60 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 2 --unit_pruning_gradient 60.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 16 --arch 8 60 60 60 60 16 --lr 0.05 --batch_size 32 --epochs 30 --seed 5 --unit_pruning_gradient 65.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 36 36 36 36 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 0 --unit_pruning_gradient 40.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 36 36 36 36 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 1 --unit_pruning_gradient 30.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 36 36 36 36 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 2 --unit_pruning_gradient 60.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 36 36 36 36 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 2 --unit_pruning_gradient 60.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 36 36 36 36 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 48 48 48 48 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 0 --unit_pruning_gradient 40.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 48 48 48 48 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 1 --unit_pruning_gradient 35.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 48 48 48 48 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 2 --unit_pruning_gradient 35.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 48 48 48 48 12 --lr 0.05 --batch_size 32 --epochs 30 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 0 --unit_pruning_gradient 25.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 0 --unit_pruning_gradient 35.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 1 --unit_pruning_gradient 5.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 1 --unit_pruning_gradient 55.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 2 --unit_pruning_gradient 25.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 2 --unit_pruning_gradient 10.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 5 --unit_pruning_gradient 30.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 12 --arch 8 60 60 60 60 12 --lr 0.05 --batch_size 64 --epochs 30 --seed 5 --unit_pruning_gradient 5.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 36 36 36 36 8 --lr 0.05 --batch_size 32 --epochs 40 --seed 0 --unit_pruning_gradient 35.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 36 36 36 36 8 --lr 0.05 --batch_size 32 --epochs 40 --seed 0 --unit_pruning_gradient 45.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 36 36 36 36 8 --lr 0.05 --batch_size 32 --epochs 40 --seed 0 --unit_pruning_gradient 35.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 36 36 36 36 8 --lr 0.05 --batch_size 32 --epochs 40 --seed 1 --unit_pruning_gradient 60.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 36 36 36 36 8 --lr 0.05 --batch_size 32 --epochs 40 --seed 1 --unit_pruning_gradient 55.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 36 36 36 36 8 --lr 0.05 --batch_size 32 --epochs 40 --seed 2 --unit_pruning_gradient 45.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 36 36 36 36 8 --lr 0.05 --batch_size 32 --epochs 40 --seed 5 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 48 48 48 48 8 --lr 0.05 --batch_size 32 --epochs 30 --seed 0 --unit_pruning_gradient 65.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 48 48 48 48 8 --lr 0.05 --batch_size 32 --epochs 30 --seed 0 --unit_pruning_gradient 60.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 48 48 48 48 8 --lr 0.05 --batch_size 32 --epochs 30 --seed 1 --unit_pruning_gradient 10.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 48 48 48 48 8 --lr 0.05 --batch_size 32 --epochs 30 --seed 2 --unit_pruning_gradient 30.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 48 48 48 48 8 --lr 0.05 --batch_size 32 --epochs 30 --seed 5 --unit_pruning_gradient 5.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 60 60 60 60 8 --lr 0.05 --batch_size 16 --epochs 40 --seed 0 --unit_pruning_gradient 65.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 60 60 60 60 8 --lr 0.05 --batch_size 16 --epochs 40 --seed 1 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 60 60 60 60 8 --lr 0.05 --batch_size 16 --epochs 40 --seed 2 --unit_pruning_gradient 45.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 8 --arch 8 60 60 60 60 8 --lr 0.05 --batch_size 16 --epochs 40 --seed 5 --unit_pruning_gradient 45.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 36 36 36 36 4 --lr 0.05 --batch_size 64 --epochs 30 --seed 0 --unit_pruning_gradient 60.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 36 36 36 36 4 --lr 0.05 --batch_size 64 --epochs 30 --seed 1 --unit_pruning_gradient 65.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 36 36 36 36 4 --lr 0.05 --batch_size 64 --epochs 30 --seed 2 --unit_pruning_gradient 10.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 36 36 36 36 4 --lr 0.05 --batch_size 64 --epochs 30 --seed 2 --unit_pruning_gradient 30.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 36 36 36 36 4 --lr 0.05 --batch_size 64 --epochs 30 --seed 5 --unit_pruning_gradient 5.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 36 36 36 36 4 --lr 0.05 --batch_size 64 --epochs 30 --seed 5 --unit_pruning_gradient 25.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 48 48 48 48 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 0 --unit_pruning_gradient 10.0 --pruning_gradient 1.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 48 48 48 48 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 1 --unit_pruning_gradient 30.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 48 48 48 48 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 2 --unit_pruning_gradient 60.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 48 48 48 48 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 5 --unit_pruning_gradient 50.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 60 60 60 60 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 0 --unit_pruning_gradient 25.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 60 60 60 60 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 1 --unit_pruning_gradient 45.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 60 60 60 60 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 1 --unit_pruning_gradient 40.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/other_structure/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 60 60 60 60 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 2 --unit_pruning_gradient 15.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 4 --arch 8 60 60 60 60 4 --lr 0.05 --batch_size 128 --epochs 40 --seed 5 --unit_pruning_gradient 15.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 60 60 60 60 2 --lr 0.05 --batch_size 64 --epochs 40 --seed 0 --unit_pruning_gradient 35.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 60 60 60 60 2 --lr 0.05 --batch_size 64 --epochs 40 --seed 1 --unit_pruning_gradient 60.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 60 60 60 60 2 --lr 0.05 --batch_size 64 --epochs 40 --seed 2 --unit_pruning_gradient 60.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 60 60 60 60 2 --lr 0.05 --batch_size 64 --epochs 40 --seed 5 --unit_pruning_gradient 25.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 48 48 48 48 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 0 --unit_pruning_gradient 65.0 --pruning_gradient 1.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 48 48 48 48 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 1 --unit_pruning_gradient 60.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 48 48 48 48 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 2 --unit_pruning_gradient 55.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 48 48 48 48 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 5 --unit_pruning_gradient 10.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/

python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 36 36 36 36 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 0 --unit_pruning_gradient 5.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 36 36 36 36 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 2.0 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 36 36 36 36 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 2 --unit_pruning_gradient 5.0 --pruning_gradient 0.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/
python3 main.py --experiment module_detection --task boolean --result_path ./results/increasing_hierarchical_levels/unit_edge/ --modularity 8 2 1 2 2 --arch 8 36 36 36 36 2 --lr 0.05 --batch_size 32 --epochs 40 --seed 5 --unit_pruning_gradient 50.0 --pruning_gradient 2.5 --feature_step_size 5 --clusterability_step_size 5 --visualization_path ./visualizations/increasing_hierarchical_levels/