python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 1.0 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 1.0 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 2 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 1.0 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 1.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 1 --unit_pruning_gradient 35.0 --pruning_gradient 0.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 2 --unit_pruning_gradient 70.0 --pruning_gradient 2.0 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 0.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 0.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 0.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 2 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 0.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 0 --unit_pruning_gradient 60.0 --pruning_gradient 0.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 2 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 1 --unit_pruning_gradient 10.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 2 --unit_pruning_gradient 25.0 --pruning_gradient 1.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 5 --unit_pruning_gradient 65.0 --pruning_gradient 0.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 0 --unit_pruning_gradient 45.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 1 --unit_pruning_gradient 55.0 --pruning_gradient 2.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 2 --unit_pruning_gradient 45.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 3 --lr 0.05 --batch_size 32 --epochs 10 --seed 5 --unit_pruning_gradient 55.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 0 --unit_pruning_gradient 50.0 --pruning_gradient 1.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 1 --unit_pruning_gradient 50.0 --pruning_gradient 1.0 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 2 --unit_pruning_gradient 45.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 24 24 24 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 5 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 0 --unit_pruning_gradient 55.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 2 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 36 36 36 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 2.0 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 1 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 2 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 6 3 3 3 --arch 6 48 48 48 3 --lr 0.05 --batch_size 32 --epochs 15 --seed 5 --unit_pruning_gradient 55.0 --pruning_gradient 1.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/