#!/bin/bash

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 0 --unit_pruning_gradient 50.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 2 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 0 --unit_pruning_gradient 25.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 1 --unit_pruning_gradient 40.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 2 --unit_pruning_gradient 25.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 5 --unit_pruning_gradient 45.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 0 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 1 --unit_pruning_gradient 60.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 2 --unit_pruning_gradient 35.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 5 --unit_pruning_gradient 10.0 --pruning_gradient 2.5 --feature_step_size 2 --clusterability_step_size 2 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 8 8 16 --lr 0.1 --batch_size 16 --epochs 120 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 8 8 16 --lr 0.1 --batch_size 16 --epochs 120 --seed 1 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 8 8 16 --lr 0.1 --batch_size 16 --epochs 120 --seed 2 --unit_pruning_gradient 45.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 8 8 16 --lr 0.1 --batch_size 16 --epochs 120 --seed 5 --unit_pruning_gradient 65.0 --pruning_gradient 1.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 12 12 16 --lr 0.1 --batch_size 8 --epochs 60 --seed 0 --unit_pruning_gradient 45.0 --pruning_gradient 1.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 12 12 16 --lr 0.1 --batch_size 8 --epochs 60 --seed 1 --unit_pruning_gradient 10.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 12 12 16 --lr 0.1 --batch_size 8 --epochs 60 --seed 2 --unit_pruning_gradient 65.0 --pruning_gradient 1.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 12 12 16 --lr 0.1 --batch_size 8 --epochs 60 --seed 5 --unit_pruning_gradient 65.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 16 16 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 0 --unit_pruning_gradient 15.0 --pruning_gradient 1.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 16 16 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 1 --unit_pruning_gradient 70.0 --pruning_gradient 1.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 16 16 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 2 --unit_pruning_gradient 60.0 --pruning_gradient 2.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 16 16 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 5 --unit_pruning_gradient 50.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 20 20 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 0 --unit_pruning_gradient 40.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 20 20 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 1 --unit_pruning_gradient 55.0 --pruning_gradient 2.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 20 20 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 2 --unit_pruning_gradient 5.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 20 20 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 5 --unit_pruning_gradient 50.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 1 --unit_pruning_gradient 25.0 --pruning_gradient 1.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 2 --unit_pruning_gradient 55.0 --pruning_gradient 2.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 5 --unit_pruning_gradient 55.0 --pruning_gradient 1.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 0 --unit_pruning_gradient 20.0 --pruning_gradient 2.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 1 --unit_pruning_gradient 65.0 --pruning_gradient 0.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 2 --unit_pruning_gradient 35.0 --pruning_gradient 1.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 5 --unit_pruning_gradient 25.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 0 --unit_pruning_gradient 55.0 --pruning_gradient 2.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 1 --unit_pruning_gradient 35.0 --pruning_gradient 2.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 2 --unit_pruning_gradient 55.0 --pruning_gradient 2.0 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 16 --lr 0.1 --batch_size 8 --epochs 20 --seed 5 --unit_pruning_gradient 60.0 --pruning_gradient 1.5 --feature_step_size 3 --clusterability_step_size 3 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 0 --unit_pruning_gradient 70.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 1 --unit_pruning_gradient 35.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 2 --unit_pruning_gradient 30.0 --pruning_gradient 2.0 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 24 24 24 16 --lr 0.1 --batch_size 8 --epochs 40 --seed 5 --unit_pruning_gradient 55.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 0 --unit_pruning_gradient 60.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 1 --unit_pruning_gradient 60.0 --pruning_gradient 0.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 2 --unit_pruning_gradient 10.0 --pruning_gradient 0.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 36 36 36 16 --lr 0.1 --batch_size 8 --epochs 30 --seed 5 --unit_pruning_gradient 35.0 --pruning_gradient 1.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/

python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 48 16 --lr 0.1 --batch_size 16 --epochs 30 --seed 0 --unit_pruning_gradient 55.0 --pruning_gradient 2.5 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 48 16 --lr 0.1 --batch_size 16 --epochs 30 --seed 1 --unit_pruning_gradient 40.0 --pruning_gradient 1.0 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 48 16 --lr 0.1 --batch_size 16 --epochs 30 --seed 2 --unit_pruning_gradient 55.0 --pruning_gradient 1.0 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/
python3 main.py --experiment module_detection --task boolean --result_path ./results/exemplar/unit_edge/ --modularity 4 1 2 16 --arch 4 48 48 48 16 --lr 0.1 --batch_size 16 --epochs 30 --seed 5 --unit_pruning_gradient 70.0 --pruning_gradient 2.0 --feature_step_size 4 --clusterability_step_size 4 --visualization_path ./visualizations/exemplar/

